language: rust

cache: cargo
  
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true

jobs:
  include:
    - stage: test
      rust: 1.30.0
      env: TARGET=x86_64-unknown-linux-gnu
      script:
        - rustup target install $TARGET
        - cargo build --target=$TARGET --release
    
    - stage: test
      rust: 1.30.0
      env: TARGET=i686-unknown-linux-gnu
      script: 
        - rustup target install $TARGET
        - cargo build --target=$TARGET --release
        
    - stage: test
      rust: 1.30.0
      os: osx
      env: TARGET=x86_64-apple-darwin
      script:
        - rustup target install $TARGET
        - cargo build --target=$TARGET
  
    # - stage: test
    #   rust: stable
    #   script: cargo build --release
  
    # - stage: test
    #   rust: beta
    #   script: cargo build --release
      
    - stage: test
      rust: nightly
      script: cargo build --release
      
    - stage: deploy
      script: skip
      on:
        - tags: true
        # - condition: 
    #   deploy:
    #     provider: releases
    #     api_key:
    #       secure: ""
    #     file_glob: true
    #     file: $CRATE_NAME-
