language: rust

cache: cargo

matrix:
  include:
    - os: linux
      rust: 1.30.0
      env: TARGET=x86_64-unknown-linux-gnu
    
    - os: linux
      rust: 1.30.0
      before_script:
        - sudo apt-get update
        - sudo apt-get install -y libc6-dev:i386
      env: TARGET=i686-unknown-linux-gnu
    
    - os: osx
      rust: 1.30.0
      env: TARGET=x86_64-apple-darwin
      
    # - os: linux
    #   rust: stable
    #   script: cargo check
    
    # - os: linux
    #   rust: beta
    #   script: cargo check
    
    - os: linux
      rust: nightly
      script: cargo check

  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true

script:
  - rustup target install $TARGET
  - cargo build --release --target=$TARGET